export interface EventValue {
    [key: string]: any;
    approvePerson: Array<string>,
    beforeOrAfter: string,
    birth: any,
    coach: string,
    competitionLevel: string,
    competitionPlace: string,
    competitionProject: string,
    competitionTime: string,
    competitionPicture: Array<string>,
    dataType: string,
    desgination: string,
    id: number,
    leader: string,
    money: string,
    name: string,
    orderBook: Array<string>,
    prizesPicture: Array<string>,
    results: string,
    resultsBook: Array<string>,
    resultsCertificate: Array<string>
    state: string,
}
export const initialEventValue: EventValue = {
    approvePerson: [],
    beforeOrAfter: '',
    birth: '',
    coach: '',
    competitionLevel: '',
    competitionPlace: '',
    competitionProject: '',
    competitionTime: '',
    competitionPicture: [],
    dataType: '',
    desgination: '',
    id: 0,
    leader: '',
    money: '',
    name: '',
    orderBook: [],
    prizesPicture: [],
    results: '',
    resultsBook: [],
    resultsCertificate: [],
    state: '',
}