export interface PersonalInfo {
    [key: string]: any,
    chineseName: string,
    sportProject: string,
    high: string,
    gender: string,
    inGroup: string,
    weight: string,
    number: string,
    nation: string,
    college: string,
    professional: string,
    aClass: string,
    birth: string,
    idCardNumber: string,
    idCardType: string,
    phone: string,
    idCardFront: string,
    idCardAfter: string,
    picture: string,
    studentReport: string,
    isSchool: string,
}
export const initialPersonalInfo: PersonalInfo = {
    chineseName: '',
    sportProject: '',
    high: '',
    gender: '',
    inGroup: '',
    weight: '',
    number: '',
    nation: '',
    college: '',
    professional: '',
    aClass: '',
    birth: '',
    idCardNumber: '',
    idCardType: '',
    phone: '',
    idCardFront: '',
    idCardAfter: '',
    picture: '',
    studentReport: '',
    isSchool: '',
}